# fly.toml app configuration file generated for publishy-bot on 2026-01-23T11:53:54+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'publishy-bot'
primary_region = 'sjc'

[build]

[env]
  NODE_ENV = 'production'

[processes]
  app = "node index.js"

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
